export const START_SCAN = 'START_SCAN';
export const STOP_SCAN = 'STOP_SCAN';
export const DEVICE_FOUND = 'DEVICE_FOUND';
export const CHANGE_DEVICE_STATE = 'CHANGE_DEVICE_STATE';
export const PUSH_ERROR = 'PUSH_ERROR';
export const POP_ERROR = 'POP_ERROR';

export const DEVICE_STATE_DISCONNECT = 'DISCONNECT';
export const DEVICE_STATE_DISCONNECTING = 'DISCONNECTING';
export const DEVICE_STATE_DISCONNECTED = 'DISCONNECTED';
export const DEVICE_STATE_CONNECT = 'CONNECT';
export const DEVICE_STATE_CONNECTING = 'CONNECTING';
export const DEVICE_STATE_CONNECTED = 'CONNECTED';
export const DEVICE_STATE_NOTIFYING = 'NOTIFYING';

export const UPDATE_BATTERY = 'UPDATE_BATTERY';
export const ADD_STRESS_VALS = 'ADD_STRESS_VALS';
export const ADD_STEPS_VALS = 'ADD_STEPS_VALS';

export const LOGIN_STATUS = 'LOGIN_STATUS';
export const LOGGED_IN = 'LOGGED_IN';
export const LOGGED_OUT = 'LOGGED_OUT';
export const INIT_USER_FB = 'INIT_USER_FB';

export const CHANGE_WIFI_STATUS = 'CHANGE_WIFI_STATUS';

export const INIT_PPG_FILE = 'INIT_PPG_FILE';
